### ISSUE TITLE
Request is not received to server from hapi-swagger UI.

### ISSUE THREAD

**Issue by saurabhghewari** [dwyl/hapi-typescript-example#1]
Great Sample, Following it for the future projects. 
I cloned the repo and started the server. Everything runs fine except request from swagger UI does not work. GET request for getting all tasks executes. No POST request is received by server.

What's the problem?  Same works fine with Pure Hapijs ES5.

**Comment by Talento90** [comment]
I've to update this repository, if you want an updated version and more completed please checkout: https://github.com/Talento90/typescript-node

I will update this repo as soon I can!
Thanks 👍

**Comment by iteles** [comment]
That would be appreciated, thanks @Talento90 !
