### ISSUE TITLE
Unable to create new routes properly

### ISSUE THREAD

**Issue by xDAnkit** [dwyl/hapi-typescript-example#10]
I tried to create routes but its not visible in swagger and even i'm not able to access it. but after sometime few of them created routes are accessible but even after removing that route code the routes are accessible don't know how.

Is this a caching issue or something else. Even i tried to create a new controller and directory but still the routes were not visible in swagger

**Comment by Talento90** [comment]
Sorry for the late answer. Can you show how are you registering the routes?

**Comment by xDAnkit** [comment]
i have fixed it long back, but missed to send an update.
