### ISSUE TITLE
how to add prefix to route

### ISSUE THREAD

**Issue by rbonillajr** [dwyl/hapi-typescript-example#2]
how to add router prefix

I added it in configuration/config.de.json and it does not work

example:
{
    "database": {
        "connectionString": "mongodb://localhost/taskdb-dev"
    },
    "server": {
        **"routes": {
            "prefix": "/api"
        },**
        "port": 5000,
        "jwtSecret": "random-secret-password",
        "jwtExpiration": "1h",
        "plugins": [
            "logger",
            "swagger",
            "jwt-auth"
        ]
    }
}

**Comment by iteles** [comment]
@Talento90 Any thoughts?

**Comment by Talento90** [comment]
It wont work like that, because I am not using directly the object server. I pick each property when I need.

If you want to support prefix you have to change the server.ts file to read the prefix route.

**Comment by Talento90** [comment]
@rbonillajr Hello, I added this feature to version 1.2.0 of my boilerplate template. 

It's just necessary to set **routePrefix**

```
    "server": {
        "port": 5000,
        "jwtSecret": "random-secret-password",
        "jwtExpiration": "1h",
        "routePrefix": "/api",
        "plugins": [
            "logger",
            "jwt-auth",
            "swagger"
        ]
    }
```
Let me know if you find any problem! 👍

**Comment by rbonillajr** [comment]
Thanks
