### ISSUE TITLE
error: uncaughtException Cannot read property 'connectionString' of undefined

### ISSUE THREAD

**Issue by leonardocintra** [dwyl/hapi-typescript-example#20]
https://github.com/leonardocintra/conservsocial-api

Help me

**Comment by xDAnkit** [comment]
**"test"** folder is missing in your scaffolding directory. Add it from forked repository and delete your **node_module** and **build** folder and try again.

Sometime what happens that when you're upgrading packages of your application with an incompatible package then such _**"connection String"**_ error occurs. So make sure to compare your package.json npm version with the reference provided. Hence delete your package.lock.json and try a fresh npm install once done with the comparision.

Take a reference from <a href="https://github.com/xDAnkit/hapi-typescript-example">here</a>

Hope it will fix your problem

**Comment by xDAnkit** [comment]
Take a reference from <a href="https://github.com/xDAnkit/hapi-typescript-example">here</a>
