### ISSUE TITLE
Plugin load order & server startup

### ISSUE THREAD

**Issue by arimus** [dwyl/hapi-typescript-example#3]
FYI, when upgrading hapi and deps I ended up with a race condition. hapi-auth-jwt2 wasn't registering the "jwt" auth mechanism before the server started up--as they are async--and the server failed to startup.

> Error: Unknown authentication strategy jwt in /tasks/{id}

I've refactored the plugin / server startup code to be promise-ified for this case. Not sure if it's an issue without the updated lib versions, but from what I can tell it may be. Might be worth mentioning or pointing out in the docs in case someone else runs into it. But if nothing else it's here.

My changes can be found here: https://github.com/arimus/hapi-typescript-example

Cheers & thanks for the bootstrap.

**Comment by Talento90** [comment]
Hi @arimus thank you very much :)

Can you make a Pull Request? 👍

**Comment by Talento90** [comment]
I have updated all the dependencies and fixed the plugin order! Thanks a lot 👍
