### ISSUE TITLE
Not able to compile

### ISSUE THREAD

**Issue by santoshanand** [dwyl/hapi-typescript-example#7]
Please have a look into following screen shot. I am not able to build this project

http://recordit.co/V31URwR3er

**Comment by Talento90** [comment]
I will give a look! Thanks a lot 👍

**Comment by Talento90** [comment]
@santoshanand weird I don't have that error! Have you cloned the last version of this project?

**Comment by alirazaalvi** [comment]
@Talento90 If you open the project in visual studio code you will find the red underline as santoshanand mentioned. When you hover on that red line it display the compiler error
"[ts]
Argument of type '{ id: any; }' is not assignable to parameter of type 'string | object | Buffer'.
  Object literal may only specify known properties, and 'id' does not exist in 
type 'string | object | Buffer'.
"

But for some reason the compiler is compiling everything properly.

**Comment by alirazaalvi** [comment]
![error](https://user-images.githubusercontent.com/1637036/27881137-a1a8ab32-61d8-11e7-8ebf-13df163fbedc.png)

**Comment by Talento90** [comment]
@alirazaalvi Thanks a lot for your contributions, I really appreciate 👍

**Comment by alirazaalvi** [comment]
Welcome :smiley:
